name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch like 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is the crucial line
    steps:
      - uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          # Install mdBook, e.g., using cargo
          cargo install mdbook --version "~0.4.0" # Use the appropriate version

      - name: Build mdBook
        run: mdbook build docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book # Or wherever your built book is located
